### ISSUE TITLE
h5预览的代码是怎么实现的

### ISSUE THREAD

**Issue by enjoyWeb** [dishait/tob-ui-doc#1]
tob-ui-doc/h5/index.html，没看懂哪里有写h5组件工程的代码

**Comment by markthree** [comment]
文档跟组件库本身是分开的，组件代码可见 👉 [tob-ui](https://github.com/dishait/tob-ui/tree/main/uni_modules/tob-ui)

**Comment by enjoyWeb** [comment]
> 文档跟组件库本身是分开的，组件代码可见 👉 [tob-ui](https://github.com/dishait/tob-ui/tree/main/uni_modules/tob-ui)

有办法实现组件库和代码在同一套代码里开发麽，比如我要新增一个组件，岂不是要去2个工程分别开发。组件库那边开发好了，要把dist挪到文档这边来预览？或者是可以直接文档里内嵌iframe是个http地址，而不是本工程的相对目录。

**Comment by markthree** [comment]
@enjoyWeb 无，你可以看看其他社区有没有类似的方案

**Comment by enjoyWeb** [comment]
> @enjoyWeb 无，你可以看看其他社区有没有类似的方案

dumi是有一个mobile的主题，但是发现vuepress没有这块的内容

**Comment by enjoyWeb** [comment]
> @enjoyWeb 无，你可以看看其他社区有没有类似的方案

dumi是给react用的，不支持其它框架

**Comment by markthree** [comment]
@enjoyWeb 移动端的只有 vuepress1有

**Comment by markthree** [comment]
vuepress-next 好像没有类似的

**Comment by enjoyWeb** [comment]
> @enjoyWeb 移动端的只有 vuepress1有

您说的vuepress1有移动端是指什么，有相关文档链接没

**Comment by markthree** [comment]
我以前找过 vuepress1 的移动端组件预览，不过现在找不到那个仓库了。

**Comment by enjoyWeb** [comment]
> 我以前找过 vuepress1 的移动端组件预览，不过现在找不到那个仓库了。

好吧，现在是弄了PC端的组件库，但是mobile端的组件库涉及到一个预览，哭了/(ㄒoㄒ)/~~

**Comment by markthree** [comment]
如果只是 `web` 端的话，可以参考 👉 [varlet](https://github.com/varletjs/varlet) 的方案

**Comment by enjoyWeb** [comment]
> 如果只是 `web` 端的话，可以参考 👉 [varlet](https://github.com/varletjs/varlet) 的方案

好的，感谢
